dev := ''
prod := ''
test := ''

docker-compose-dev:
	docker compose --env-file $(dev) -f docker-compose.yaml up -d


docker-compose-prod:
	docker compose --env-file $(prod) -f docker-compose.yaml up -d


docker-compose-test:
	docker compose --env-file $(test) -f docker-compose.yaml up -d


docker-compose-down:
	docker compose --env-file $(dev) -f docker-compose.yaml down --rmi "local"