docker-compose-dev:
	docker compose -f docker-compose.yaml up -d


docker-compose-prod:
	docker compose -f docker-compose.yaml up -d


docker-compose-test:
	docker compose -f docker-compose.yaml up -d


docker-compose-down:
	docker compose -f docker-compose.yaml down --rmi "local"